version: "3.9"  
services:
  mongo:
    image: mongo:4.4.15
    restart: always
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    networks:
      - backend
  mongo-express:
    image: mongo-express
    restart: always
    env_file:
      - .env
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongo:27017/
    networks:
      - backend
  rabbitmq:
    image: rabbitmq:3-management-alpine
    env_file:
      - .env
    ports:
      - 5672:5672
      - 15672:15672
    environment: 
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq/
      - rabbitmqlog:/var/log/rabbitmq
    networks:
      - backend
  nova:
    build:
      context: ./nova
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./nova:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${NOVA_PORT}:${NOVA_PORT}
      - 9229:9229
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - backend
    depends_on:
      - rabbitmq
      - mongo
networks:
  backend:
    driver: bridge
volumes:
  rabbitmqdata:
  rabbitmqlog:
